#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp status => "
        echo `cat <<EOT
Shows the status of every NITA Webapp containers.
EOT` >&2
