#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp db cli => "
        echo `cat <<EOT
Create an interactive session in the db pod by executing a bash shell.
EOT` >&2
