#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp up => "
        echo `cat <<EOT
Stops and removes the running NITA Webapp service, according to the configuration file in $NITAWEBAPPDIR
EOT` >&2
