#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp logs => "
        echo `cat <<EOT
Follows log output of webapp container.
EOT` >&2
