#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp start => "
        echo `cat <<EOT
Starts the NITA Webapp pod.
EOT` >&2
