#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp cli => "
        echo `cat <<EOT
Create an interactive session in the webapp container by executing a bash shell and using stdin as a tty.
EOT` >&2
