#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp restart => "
        echo `cat <<EOT
Restart the NITA Webapp with zero downtime by starting a new pod before terminating the old one.
EOT` >&2
