#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
        echo -n "    nita-cmd webapp labels => "
        echo `cat <<EOT
Returns labels information on webapp container.
EOT` >&2
