#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Priority order is top down

if [ -x "$(command -v kubectl)" ]; then

    export POD=$(kubectl get pods -n nita --no-headers=true -l io.kompose.service=proxy | grep Running | awk '{print $1}')
    CMD="kubectl exec -it $POD -n nita -- /bin/bash"

elif [ -x "$(command -v docker)" ]; then

    CMD="echo Unsupported command"

else

  echo 'Error: cannot find required binaries.' >&2
  exit 1

fi

[ ${_CLI_RUNNER_DEBUG} ] && echo ${CMD}>&2

eval "${CMD}"
