#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Priority order is top down

if [ -x "$(command -v kubectl)" ]; then
    
    CMD="kubectl delete -f ${NITAWEBAPPDIR-/opt/nita/k8s}/webapp-deployment.yaml"

elif [ -x "$(command -v docker)" ]; then

    CMD='docker-compose -p nitawebapp -f ${NITAWEBAPPDIR-/etc/nita-webapp}/docker-compose.yaml down'

else

  echo 'Error: cannot find required binaries.' >&2
  exit 1

fi

[ ${_CLI_RUNNER_DEBUG} ] && echo ${CMD}>&2

eval "${CMD}"
