#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Priority order is top down

if [ -x "$(command -v kubectl)" ]; then

    # Rollout starts a new pod before terminating the old one
    CMD="kubectl rollout restart deployment/webapp -n nita"

elif [ -x "$(command -v docker)" ]; then

    CMD='docker-compose -p nitawebapp -f ${NITAWEBAPPDIR-/etc/nita-webapp}/docker-compose.yaml restart'

else

  echo 'Error: cannot find required binaries.' >&2
  exit 1

fi

[ ${_CLI_RUNNER_DEBUG} ] && echo ${CMD}>&2

eval "${CMD}"
