[pytest]
DJANGO_SETTINGS_MODULE = ngcn_workbench.test_settings
pythonpath = build-and-test-webapp/nita-webapp/ngcn_workbench
testpaths = build-and-test-webapp/nita-webapp/ngcn_workbench/tests
python_files = test_*.py
addopts = -ra
