#!/bin/bash
if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
docker images --filter "label=net.juniper.framework=NITA"
EOT` >&2
fi
docker images --filter "label=net.juniper.framework=NITA"