#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd restore <filename> "
        echo `cat <<EOT
Restores from <filename> the folders backed up using the backup command
EOT` >&2
