#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd images versions => "
        echo `cat <<EOT
Displays NITA images versions.
EOT` >&2
