#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
docker ps -q --filter "label=net.juniper.framework=NITA" | xargs docker inspect | jq '.[] | "\(.Name) \(.NetworkSettings.Networks[].IPAddress)"'
EOT` >&2
fi
docker ps -q --filter "label=net.juniper.framework=NITA" | xargs docker inspect | jq '.[] | "\(.Name) \(.NetworkSettings.Networks[].IPAddress)"'