#!/bin/bash
if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
docker stats --no-stream $(docker ps -q --filter "label=net.juniper.framework=NITA" --format={{.Names}})
EOT` >&2
fi
docker stats --no-stream $(docker ps -q --filter "label=net.juniper.framework=NITA" --format={{.Names}})