#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

VERSION=22.8
if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
echo nita-cli $VERSION
EOT` >&2
fi
echo nita-cli $VERSION
