#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd containers versions => "
        echo `cat <<EOT
Lists all running NITA containers versions.
EOT` >&2
