#!/bin/bash
if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
echo `cat <<EOT
docker images -q --filter "label=net.juniper.framework=NITA" | xargs docker inspect | jq '.[] | "\(.RepoTags[0]) \(.Id)"'
EOT` >&2
fi
docker images -q --filter "label=net.juniper.framework=NITA" | xargs docker inspect | jq '.[] | "\(.RepoTags[0]) \(.Id)"'
