#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd images ls => "
        echo `cat <<EOT
Lists all NITA images.
EOT` >&2
