#!/bin/bash
if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
docker ps -q --filter "label=net.juniper.framework=NITA" | xargs docker inspect | jq '.[] | "\(.Name) \(.NetworkSettings.Networks[].IPAddress)"'
EOT` >&2
fi
docker ps -q --filter "label=net.juniper.framework=NITA" | xargs docker inspect | jq '.[] | "\(.Name) \(.NetworkSettings.Networks[].IPAddress)"'