#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd cli version => "
        echo `cat <<EOT
Shows NITA CLI current version.
EOT` >&2
