#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd ips => "
        echo `cat <<EOT
Shows all NITA containers IPs.
EOT` >&2
