#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

        echo -n "    nita-cmd license => "
        echo `cat <<EOT
Displays the NITA License.
EOT` >&2
