#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
docker images --filter "label=net.juniper.framework=NITA"
EOT` >&2
fi
docker images --filter "label=net.juniper.framework=NITA"