#!/bin/bash
# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

if [ "$_CLI_RUNNER_DEBUG" == 1 ]; then
        echo `cat <<EOT
docker ps --filter "label=net.juniper.framework=NITA" --format "table {{.ID}}	{{.Image}}	{{.RunningFor}}	{{.Status}}	{{.Ports}}	{{.Names}}"
EOT` >&2
fi
docker ps --filter "label=net.juniper.framework=NITA" --format "table {{.ID}}	{{.Image}}	{{.RunningFor}}	{{.Status}}	{{.Ports}}	{{.Names}}"