apiVersion: v1
kind: Service
metadata:
  name: robot
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080 
    protocol: TCP      
  selector:
    app: robot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot
  template:
    metadata:
      labels:
        app: robot
    spec:
      containers:
      - name: robot
        image: juniper/nita-robot:21.7-1
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - name: robot-vol
            mountPath: /var/robot_vol
      volumes:
        - name: robot-vol
          emptyDir: {}