apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000 
    protocol: TCP      
  selector:
    app: webapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pv-claim
  labels:
    app: webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv-volume
  labels:
    app: webapp
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: juniper/nita-webapp:21.7-1
        command: ["/bin/sh"]
        args: ["-c", "./build-and-test-webapp/wait-for-db.sh"]
        env:
          - name: DJANGO_LOG_LEVEL
            value: DEBUG
          - name: JENKINS_PASS
          - name: JENKINS_PORT
          - name: JENKINS_URL
          - name: JENKINS_USER
          - name: WEBAPP_PASS
          - name: WEBAPP_USER
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: mysql-pass
                 key: password
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - name: webapp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: webapp-persistent-storage
        persistentVolumeClaim:
          claimName: webapp-pv-claim