# Copyright (c) Hewlett Packard Enterprise, 2026. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
[jenkins.server.details]
hostname=jenkins
port=8080
[environment.details]
#'vagrant' or 'standalone' for respective build type
build_type=vagrant
[project.details]
#path=/home/vagrant
path=/project
