apiVersion: v1
kind: Service
metadata:
  namespace: nita
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  type: ClusterIP
  selector:
    io.kompose.service: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
