---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-jenknis-pod
  namespace: nita
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-pods
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-jenknis-pod
    namespace: nita
roleRef:
  kind: ClusterRole
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
