apiVersion: v1
kind: Service
metadata:
  namespace: nita
  name: webapp
  labels:
    io.kompose.service: webapp
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    io.kompose.service: webapp
  type: ClusterIP
