name: Branch workflow

on:  
  create:
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Echo
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
      
      - name: Set VERSION.txt
        shell: bash
        run: echo "WORKSPACE=${GITHUB_WORKSPACE}" ; cd ${GITHUB_WORKSPACE} ; ./build-end-test-webapp/update_version.sh   

