name: Release workflow

on:  
  release:
    types: [created]
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Echo
        shell: bash
        run: echo "TAG=${GITHUB_REF:-${GITHUB_REF#refs/tags/}}"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set VERSION.txt
        shell: bash
        run: cd ${GITHUB_WORKSPACE} ; bash ./build-and-test-webapp/update_version.sh   

